### ISSUE TITLE
Dokan running on pyfilesystem 2

### ISSUE THREAD

**Issue by merlink01** [PyFilesystem/pyfilesystem2#115]
Thx to Liryna:
https://github.com/Liryna/pyfilesystem

I got her code running in pyfilesystem 2.
https://github.com/merlink01/pyfilesystem2

Tested on python 3.5 (32Bit), Dokan V1.1.0.1000
Who is interested could have a look.
Bugfixes are welcome.

**Comment by Liryna** [comment]
@merlink01 Thats awesome ! :open_mouth: Great work and thank you !

**Comment by merlink01** [comment]
Added new exposed module: httpserver
Also started portation of Fuse (not mountable jet)

**Comment by althonos** [comment]
@merlink01 @lyrna : when I get some time on m'y hand, i'll try to see if this can be embedded into an independent extension module

**Comment by merlink01** [comment]
@althonos this would be really cool.
Both running modules (dokan + httpserver) habe no external dependencies. Should they be stand Alone packages or one big exposed module? I think one packages per Module would be best, right?

**Comment by althonos** [comment]
How about `fuse` ? Are you relying on a ctypes interface or will you be using one of the existing library wrappers ?

I think we could have each expose package declare a `fs.expose` namespace so that they could work well with each other. But there could also be a way to independently manage each package. It would also be interesting for each module to have a practical CLI, so that FS could be exposed directly by calling the `fs.expose` module. 

Also, for the `httpserver`, there's an existing solution using [moya](https://github.com/moyaproject/moya), but I think it's okay to also have a solution with a lot less dependencies.

**Comment by althonos** [comment]
@merlink01: started porting the code into an independent module, see [althonos/fs.expose](https://github.com/althonos/fs.expose).

I will centralise the development of all the packages, but release them independently under the `fs.expose` namespace.

I started porting the `http` code to Python 2, and it seems to work with a few modifications. I'll do the same for the `dokan` code, and then setup Travis and Appveyor.

**Comment by merlink01** [comment]
@althonos this is really great.

Thank you very much.

After httpserver is online, I try to port xmlrpcserver next.

Fuse will be the next big step, but there I need more time :-)

**Comment by althonos** [comment]
@merlink01: I implemented a fuse driver, the code seem to work but it needs polish and tests. 

This issue should probably be closed in favour of the `fs.expose` issue tracker. Feel free to send PRs or issue tickets there.

**Comment by willmcgugan** [comment]
Thanks @merlink01 @Liryna @althonos This would be a really valuable addition to the project. I concur that a separate package is they way to go in order to keep the dependancies of the core lib down to a minimum.

Let me know if I can be any help.

**Comment by merlink01** [comment]
Yes, thanks to all.
I will close this issue now and hope wie will geht a nice collection oft Expose modules on our New place:
https://github.com/althonos/fs.expose
