### ISSUE TITLE
usercache error

### ISSUE THREAD

**Issue by igmanbe** [PyFilesystem/pyfilesystem2#156]
I'm running an OSX High Sierra with python 2.7. When I try to use FS I'm getting this error:

python -c "import fs; fs.open_fs('usercache://')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 179, in open_fs
    default_protocol=default_protocol
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 136, in open
    opener = self.get_opener(protocol)
  File "/Library/Python/2.7/site-packages/fs/opener/registry.py", line 75, in get_opener
    "protocol '{}' is not supported".format(protocol)
fs.opener.errors.UnsupportedProtocol: protocol 'usercache' is not supported

**Comment by althonos** [comment]
Related issue is althonos/InstaLooter#151.

Occurs when using an old `distribute` version (an old and unmaintained fork of `setuptools`), which will inject itself in lieu of `setuptools` when installing the module. This causes the entry points declared in the `setup.py` to be ignored at install time (not sure of this, but I think).

To be honest, I'm not sure this issue really does require us to add a safeguard to the setup file, as `distribute` is deprecated since 2013. But it could probably be feasible to check in `setup.py` that `setuptools` is really `setuptools`.

**Comment by willmcgugan** [comment]
Going to close this for now.
