### ISSUE TITLE
PyFilesystem can't find existing file in tar-fs

### ISSUE THREAD

**Issue by Rhavatu** [PyFilesystem/pyfilesystem2#160]
I wrote a stackoverflow post about this, I'm not entirely sure, but I suspect this to be a bug:

https://stackoverflow.com/questions/49811622/pyfilesystem-cant-find-existing-file-in-tar-fs

**Comment by althonos** [comment]
This is indeed a bug, the `VSCode-linux-x64/.../diagnostic-channel` is an inferred directory, so it does not exist within the tarfile, and to `tarfile.getmember(...)` crashes.

`TarFS` should handle these properly, I'll submit a patch.

**Comment by Rhavatu** [comment]
Thank you :) 
I tried to google inferred directory, but didn't find anything. What exactly is an inferred directory?

**Comment by althonos** [comment]
That's not the exact term, but I used that to describe a mecanism used by tar archives:

basically, tar archives are a collection of files, refered to by their absolute path within the archive. For instance, if the archive has two members
```
/foo.txt
/bar/baz.txt
```
then you have to infer that `bar` is a directory within the archive.

But since you may want to attribute special permissions or whatever to a directory, it is also possible to add a directory to the tar archive by declaring it to be of `DIRTYPE`: for instance the same archive could come as 
```
/foo.txt
/bar/
/bar/baz.txt
```
and still have the same structure.

So I refer to the first case as an *inferred* directory, and to the second as a *declared* directory (but that's just me trying to find a good description for both cases when I fill comments within the source).

**Comment by Rhavatu** [comment]
Ok, thanks for the clarification :+1:

**Comment by althonos** [comment]
By the way, I patched [`fs.archive`](https://github.com/althonos/fs.archive) so that it should work now (at least it works with your StackOverflow test case).

To try it, install `fs.archive==0.3.2` and then import `TarFS` from `fs.archive.tarfs` in your failing test case.

I'll open a PR so that the patch is merged into the `fs` codebase.

**Comment by Rhavatu** [comment]
Awesome, works like a charm!
