### ISSUE TITLE
Support for DockerFS?

### ISSUE THREAD

**Issue by xandfury** [PyFilesystem/pyfilesystem2#203]
Docker seems to be a popular option for keeping/playing with files depending upon the use case. Do you think, a docker fs wrapper implementation can be considered as a feature request?

**Comment by willmcgugan** [comment]
As a general rule, the main lib will only support filesystems that can be built with the stdlib. If it needs external code, particularly C extensions, it can be distributed as an external module.

I didn't know there was a DockerFS per se. I thought it used Linux filesystems that may be mounted by the OS. In that case you could just use OSFS...

**Comment by althonos** [comment]
I think you can mount a host directory in the docker image filesystem, but I've never done it the other way around, mounting the image filesystem in a host directort. If it's feasible, then it's just a matter or having a derived `TempFS` that mounts the docker image to its root directory when created, and unmounts it when closed, using the Python docker client (I've some experience with it).

(And since docker can be interacted with using a socket, it could be feasible only using the stdlib, but that would be extremely stupid considering how rich their API is and how feature-rich their Python wrapper is ahah)
