### ISSUE TITLE
tahoe-lafs

### ISSUE THREAD

**Issue by eleaner** [PyFilesystem/pyfilesystem2#212]
Hi

I noticed that tahoe-lafs support was dropped in version 2
Is there a chance it will come back?

**Comment by willmcgugan** [comment]
I don't think it will come back as part of this module. Purely because in version 2 I'm keeping the core leaner with minimal dependancies.

It would be great to see it ported to PyFilesystem2 however, as part of the PyFilesystem org or by a third party. If you need it for a commercial project, I am available for contract work.
