### ISSUE TITLE
Support of ReadOnly File System?

### ISSUE THREAD

**Issue by Nazime** [PyFilesystem/pyfilesystem2#355]
I discovered this project few days ago and I find it really **interesting**.

I am working on a project and need to implement/use a read only github file system. I almost finished the read only class from scratch (isdir, ispath, listdir, readtext, ...) and it's very unfortunate that I can't use pyfilesystem2 and all its features or to add my project as an extension to pyfilesystem2.

I couldn't use pyfilesystem for two reasons

- must implement none read only methods (makedir, remove, ...)
- no unitesting for readonly file systems

Is there any way to support ReadOnly filesystem?

This is an overview of the Github read only filesystem 
```python
from rofs import GithubROFS
pyfilesystem2 = GithubROFS("pyfilesystem/pyfilesystem2")  # github repo
pyfilesystem2.isdir("docs")  # True
pyfilesystem2.isdir("docs/source")  # True
pyfilesystem2.isdir("none")  # False
pyfilesystem2.isfile(".gitignore")   # True

```

**Comment by dargueta** [comment]
> must implement none read only methods (makedir, remove, ...)

You don't need to do anything in the methods that would write to the file system, e.g. `makedir`. You can have them immediately throw an exception:

```py
from fs.errors import ResourceReadOnly

def makedir(self, path, permissions=None, recreate=False):
    raise ResourceReadOnly(path)
```

> no unitesting for readonly file systems

What do you mean?

**Comment by chfw** [comment]
Have you checked out this project? https://github.com/moremoban/gitfs2

**Comment by willmcgugan** [comment]
@Nazime We do have a mechanism for making a filesystem read only (https://docs.pyfilesystem.org/en/latest/reference/wrap.html). As @dargueta pointed out, you can raise the `ResourceReadOnly` exception for methods that might otherwise write to the filesystem.

> no unitesting for readonly file systems

It is true you can't re-use the tests in `fs.tests` for your custom read only filesystem. You would have to write the test yourself. It would be nice to have a test suite for read only filesystems, but its not clear to me how that would be implemented. If you can't write to the filesystem, how can you set up the test data? If you have any suggestions for a generic test suite for read only filesystems, let us know.

**Comment by Nazime** [comment]
@dargueta I was talking about fs.tests like class for ReadOnly FileSystem. @willmcgugan for testing my ReadOnly FileSystem, I did a generic FileSystem that I will reproduce in each ReadOnly class to have the same suite of tests. I don't know if it's a good idea, but it works fine for me.

The structure look like this

```
/
    dir1/
        dir4/
            emptyfile
        f4
    dir2/
        f5
        f6  
    dir3/
        f7[test]
    f1
    f2
    f3
    README.md
    LICENSE
```

And the class Test look like this

```python
class TestROFS:
    def make_rosf(self):
        raise NotImplementedError

    def test_isdir(self, fs):
        assert fs.isdir("dir1")
        assert fs.isdir("/dir1")

        assert fs.isdir("dir1/dir2")
        assert fs.isdir("/dir1/dir2")
        assert not fs.isfile("f1")

    def test_isfile(self, fs):
        assert fs.isfile("f1")

    def test_listdir(self, fs):
        expected = ["dir1", "dir2", "dir3", "f1", "f2", "f3", "README.md", "LICENSE"]
        assert sorted(fs.ls()) == sorted(expected)

    ...

```

Then I uploaded a github repo to test it https://github.com/Nazime/test_pypoke_01

 ```python
class TestGithubROFS(TestROFS):
    def make_rosf(self):
        return GithubROFS("nazime/test_pypoke_01")

# Testing an other ReadOnly FileSystem that share the same structure
class TestGitrepoROFS(TestROFS):
    def make_rofs(self):
        return Gitrepo("~/github/test_pypoke_01")

```

In order to create a ReadOnly FileSystem the developer must recreate the same structure.

@chfw I am going to check the project

**Comment by lurch** [comment]
>  If you can't write to the filesystem, how can you set up the test data? If you have any suggestions for a generic test suite for read only filesystems, let us know.

I guess you'd need to set up a filesystem in advance (e.g. a zip archive if testing a ReadOnly ZipFS) with a known hierarchy and contents, and then the read-only tests would check that the files and folders read by the FS being tested then matched what was expected. Although I guess unless you can guarantee each pre-prepared filesystem has the same contents, this would need to be FS-specific rather than a generic set of tests for all ReadOnly FSes. Although I guess a generic RO test could check that each method which would attempt to modify the FS threw a `ResourceReadOnly` exception :wink:

**Comment by lurch** [comment]
@Nazime Yeah, back in the pyfilesystem1 days I often wondered why there wasn't a read-only base FS class, with a read-write base FS class layered on top of that. But too late to change now ;-) (and I guess throwing exceptions is a useful workaround)

**Comment by Nazime** [comment]
@lurch I just edited the typo. Yes, it would have been great to have the base class as read only.
But we can add support for ReadOnly class, create a ReadOnlyFS class that throw exceptions for write methods, having basic tests suite for it and maybe document it a little bit.
