### ISSUE TITLE
Inconsistency between filenames being represented as listdir() output vs. walker.files()

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/pyfilesystem2#375]
I found an edge case that popped with the `webdavfs` driver and a faulty WebDAV server (Zope 5).
The problem is the the WebDAV server exposes the filename of a resource (through the `displayname` tag in XML as `b'bar.txt' - possibly to some improper str to bytes conversion in Zope.

So the output of listdir() seems to derive the name of a file in a different way than the `Walker.files()` implementation. Neither checked the pyfilesystem nor the WebDAV code...do you have an idea if this is an issue in PyFilesystem2 or our driver?

```
(Pdb) handle.listdir(".")
['bar.txt']

(Pdb) for x in walker.files(handle): print(x)
/b'bar.txt'

(Pdb) handle.getinfo('bar.txt')
<file 'b'bar.txt''>

(Pdb) handle.getinfo('bar.txt').name
"b'bar.txt'"

 ```

**Comment by willmcgugan** [comment]
Hi @zopyx That issue is unlikely to be in PyFilesystem. I see webdavfs has both `getinfo` and `listdir` implemented, and they call different methods on the webdav client. I'd try printing out the raw result of those calls.

If you see the "b'bar.txt'" in the raw data then that would point the finger at the `webdav2` module or the server. That particular encoding error is generally the result of converting bytes to unicode with `str(my_bytes)`, which worked in Python2, but doesn't in Python3.

**Comment by zopyx** [comment]
The offending problem was clearly the broken WebDAV implementation in Zope. The problem is now resolved with a fix in Zope.
