### ISSUE TITLE
Replace Travis-CI with another CI provider

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#446]
Hi @PyFilesystem/maintainers ,

With Travis-CI now in the hands of a private equity firm, OSS builds are being phased out, so we need a new CI provider. 

## AppVeyor

AppVeyor still works well for Windows (although the environment itself is a bit outdated, `appveyor.yml` should be updated to test on more recent Python versions as well). However, I don't know if you can test on both Linux and Windows, and I don't feel like it's the common case to use AppVeyor for Linux builds anyway.

## GitHub Actions

I have no experience with Actions, but to quote [Kat Maddox](https://twitter.com/ctrlshifti/status/1322859969872449536):

> devops is when you write yaml. the more yaml you write, the more devopsier it is

So i assume it works like any other CI, and would be in favour of migrating towards this unless some of you have a bad experience with it or a better platform to suggest.

## Circle-CI

Circle-CI has a build-time limit per week, but since Pyfilesystem2 is not the most active of projects I don't think we would reach it. It could be a good alternative as well.

**Comment by zopyx** [comment]
My preference would be clearly Github Actions since it is directly with Github und provides basically the same what we have and need on Travis-CI with a tighter integration. We are using Github actions in a few customer projects and we are fine with it. I tried to move my WebDAV driver a time ago to Github actions but failed at some point with the GH integration of Docker (which is needed for the WebDAV driver tests for testing against various real world WebDAV servers).
