### ISSUE TITLE
ZipFS has a `syspath` and `ospath`

### ISSUE THREAD

**Issue by tfeldmann** [PyFilesystem/pyfilesystem2#528]
As discussed in #523, normally ZipFS should have no syspath and a `NoSysPath` exception should be raised.

```python
>>> import fs
>>> x = fs.open_fs("zip://test.zip", create=True)
>>> x.getospath("/")
b'/var/folders/lt/sg8874fn2lz5y3wcphs91j440000gn/T/tmpvdg2plgy__ziptemp__/'
>>> x.getsyspath("/")
'/var/folders/lt/sg8874fn2lz5y3wcphs91j440000gn/T/tmpvdg2plgy__ziptemp__/'
```

**Comment by lurch** [comment]
Do you fancy submitting a suitable PR?

**Comment by althonos** [comment]
Ah, okay, I see what i was talking about in #523, but I'm not entirely sure this current situation is to be treated as a bug... 

When you open a Zip file, you get a `ReadZipFS` which doesn't have a syspath because files are decompressed on request. But when you create a new Zip file from scratch, you get a `WriteZipFS`, which is actually a simple wrapper around a temporary filesystem which will be compressed when closed. 

So if the temporary filesystem is a temp folder, it makes sense that you have a syspath. It also enables efficient copying / moving files that are going to be compressed. There will be no syspath in the event where you use a temporary filesystem in memory to prepare the archive:
```python
zip_fs = fs.zipfs.WriteZipFS("/tmp/test.zip", temp_fs="mem://")
```

**Comment by tfeldmann** [comment]
I see! Then the question is what went wrong with ZipFS in my optimization tests. I'll try to reproduce it.

**Comment by tfeldmann** [comment]
Closing this as a non-issue. ZipFS having a syspath when wrapping a temp filesystem is fine.
