### ISSUE TITLE
ZipFS - Set compression for single file

### ISSUE THREAD

**Issue by geoffjukes** [PyFilesystem/pyfilesystem2#543]
Hi!

I'm trying to use ZipFS to write ePub files. In the spwc, the first file in the Zip HAS to be `mimetype` and it must not be compressed (i.e. has to be `ZIP_STORED`). Other files need to be `ZIP_DEFLATED`

I can create a valid Zip using zipfile.ZipFile, because I can set the compression when I write a file. But I'm having a hard time with ZipFS. This doesn't work:

```python
            with fs.zipfs.ZipFS(_zip_file, write=True, compression=zipfile.ZIP_STORED) as _zip:
                _zip.writetext('mimetype', 'application/epub+zip')
                # Change compression...
                _zip.compression = zipfile.ZIP_DEFLATED
                # ...and add the content
                fs.copy.copy_fs(_skel, _zip)
```
The resulting Zip has `mimetype` `ZIP_DEFLATED`:

![image](https://user-images.githubusercontent.com/1959570/178941780-f84c83eb-7fe1-44c6-92a6-9adc3427ee5f.png)

I also tried opening the Zip file twice, once for each compression - but that results in a corrupt file.

Is this a bug, or am I doing something that it's not intended to support?

I have a way to work around it with zipfile.ZipFile - but this looked so neat :)

**Comment by lurch** [comment]
Looks like the `compression` option is only used when the zipfile is actually written, which happens (in a single step) when you close the ZipFS. https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/zipfs.py#L328

IMHO this "zip customisation" isn't really a good fit for pyfilesystem, because even if you _could_ overwrite the compression on a per-file basis, there's probably no easy way to guarantee that the `mimetype` is the first file written into the zipfile. Unless you created a WriteEpubFS or something... :wink:

**Comment by geoffjukes** [comment]
Thanks @lurch , that makes sense. I'll go back to the zipfile solution, no biggie - I can use a 'temp://' filesystem ;)
