### ISSUE TITLE
Feature Request: FUSE and/or WebDAV server

### ISSUE THREAD

**Issue by Jwink3101** [PyFilesystem/pyfilesystem2#567]
It would be super useful if there was  built in FUSE mounting or WebDAV (local loopback intended) serving of the file systems. There are a few Python FUSE and Python WebDAV libraries out there but they are nowhere near as nicely documented as PyFilesystem and the abstraction is not as good.

A server written to directly to interface would be super useful!

**Comment by lurch** [comment]
> A server written to directly to interface would be super useful!

I agree, but unfortunately see https://github.com/PyFilesystem/pyfilesystem2/issues?q=is%3Aissue+fuse+is%3Aclosed

**Comment by lurch** [comment]
And https://github.com/fusepy/fusepy/issues/134 (which is an issue from almost 4 years ago!) shows what a confusing state FUSE support on Python is :cry:  Following the links to various projects / forks mentioned there, I find that:
* https://github.com/fusepy/fusepy ("Simple ctypes bindings for FUSE") hasn't had any code-commits since 2018
* https://github.com/libfuse/python-fuse ("Python 2.x/3.x bindings for libfuse 2.x") had a code-commit in April 2022
* https://github.com/python-llfuse/python-llfuse/ ("Python bindings for the low level FUSE API") had a code-commit in July 2022 but its README says "Warning - no longer developed!"
* https://github.com/libfuse/pyfuse3 ("Python 3 bindings for libfuse 3 with asynchronous API (Trio compatible)") had a code-commit in October 2022 but its README says "Warning - no longer developed!"
* https://github.com/pleiszenburg/refuse ("Simple cross-plattform ctypes bindings for libfuse / FUSE for macOS / WinFsp") hasn't had any code-commits since July 2020
* https://thelig.ht/code/fusepyng/ ("Simple ctypes bindings for FUSE") had a code-commit in January 2022
* https://github.com/paulo-raca/fusetree ("A better Fuse API for Python 3") hasn't had any code-commits since March 2020

**Comment by Jwink3101** [comment]
This just further supports my point that it is an utter mess!  I appreciate that it’s a lot of work but it would perfectly fit the abstraction of PyFilesystem!

I wonder if implementing WebDAV or NFS would be easier. It’s less integrated than FUSE but seems like it would allow for a cleaner separation.

**Comment by lurch** [comment]
> This just further supports my point that it is an utter mess! I appreciate that it’s a lot of work but it would perfectly fit the abstraction of PyFilesystem!

Yes, and PyFilesystem1 (which is no longer maintained) did support that via a bunch of `fs.expose` classes , but it looks like they were too much effort to update for PyFilesystem2.
https://pyfilesystem.readthedocs.io/en/latest/expose.html
https://pyfilesystem.readthedocs.io/en/latest/contrib/davfs.html

Contributions welcome! :slightly_smiling_face:

**Comment by Jwink3101** [comment]
I didn't realize that is what the old expose did. It is very much along the lines of what I'd like to see. 

There are some WebDAV utilities out there. I have a short break coming up and I may see how hard they are to get working and if I can, I can hook it up to the abstraction. 

However, I do see this is a duplicate so I'll close this (unless you want to reopen it as a future task)

See #274, #115, #17

**Comment by lurch** [comment]
>  I may see how hard they are to get working and if I can, I can hook it up to the abstraction.

Note that you'll be **providing** a filesystem, rather than **consuming** a filesystem, so it won't just "plug in" to the existing PyFilesystem2 API. (if you see what I mean!)
