### ISSUE TITLE
scandir and container_files

### ISSUE THREAD

**Issue by jdonnerstag** [PyFilesystem/pyfilesystem2#59]
Hi,

this might be the wrong place for this discussion. In case please suggest a more appropriate one.

We have some special requirements which we plan to build on top of pyfs2, and we hope you have some good ideas on how to achieve / implement this.
- We only need to read the data
- A scandir like function that **transparently** treats container files (*.tar.gz; *.zip) very much like a directory
- Whatever the iterator returns must include the full "virtual" path, e.g. /xxx/data.tar.gz/subdir/myfile and the fd related to the file (please see below for why that is)
- Some of our tar.gz files are (very) large and we'd like to use streaming (mode="r|*"). Based on previous experience this is significantly faster for our use case and setup. Streaming however comes with a caveat: seek()/tell() is not allowed and thus the iteration order is the order in which the files were added to the container file. That limitation is fine for us. 
- Due to the streaming requirement the my_scandir iterator needs to return a tuple of fd and info, rather then the filename. Using the filename to open requires seek/tell.
- This fd + info approach raises some issues with nested container files, because pyfs2 fs.open(path) does not support fd/fileobj, but only path. Python Tarfile does support tarfile.open(name=.., fileobj=...). This is required for nested container files only (unfortunately we are not able to change that).
- To my understanding streaming is currently only supported in python for tar-files , not for zip files. Which is fine for us. Where not supported, silently apply fd = fs.open(path).
- It is fine for us if the fd is a binary stream. We apply TextIOWrapper at a later stage where necessary

Do you have some good ideas on how to easily achieve this?

thanks a lot
Juergen

**Comment by willmcgugan** [comment]
> Do you have some good ideas on how to easily achieve this?

Not sure about *easily*, but I'm sure its achievable!

So I gather you don't need some kind of virtual filesystem where the archives appear to be directories, and its just the directory walking that should create the illusion of a single filesystem?

You might want to start with a copy of the code in `walk.py` and modify it so that when you encounter an archive, you defer another generator to walk through the tar file. That way you can implement your requirements around needing the fd.

Otherwise, I think your requirement of streaming the files will make it impossible to fit in to a FS2 interface.

If you didn't have that requirement, then it would be a simpler task. You may even be able to use a MountFS to mount the zip/tar files as you encounter them.

You could try the mailing list (pyfilesystem-discussion@googlegroups.com) if you want further suggestions....

**Comment by willmcgugan** [comment]
Going to close this. Would be interested in knowing if you made progress...

**Comment by jdonnerstag** [comment]
Unfortunately no break through yet. I had several attempts, but the source code was always either clumsy, or inconsistent or felt more complicated then it should be. So I'm still searching for an elegant way of implementing the requirements

Juergen
