### ISSUE TITLE
Symlinks are not detected

### ISSUE THREAD

**Issue by parisk** [PyFilesystem/pyfilesystem2#61]
It seems that `pyfilesystem2 ` does not detect symlinks, while the stock Python modules do.

Any ideas, why this might be happening and how can it get fixed.

## Example

**Python version**: 3.6
**System**: Inside Docker container in Docker for Mac

### Code
```
In [19]: from fs import osfs

In [20]: from pathlib import Path

In [21]: root = osfs.OSFS('/')

In [22]: Path('/usr/local/bin/python').is_symlink()
Out[22]: True

In [23]: root.gettype('/usr/local/bin/python')
Out[23]: <ResourceType.file: 2>
```

**Comment by parisk** [comment]
It seems like something weird is happening here, so I moved on and asked a question on StackOverflow: https://stackoverflow.com/questions/45358462/python-3-does-not-detect-symlinks-via-stat.

Any idea @willmcgugan?

**Comment by willmcgugan** [comment]
The FS interface isn't aware of symlinks, and OSFS just follows them by default.

I would like to add symlink support, in such a way that it doesn't complicate other filesystems that don't have a concept of 'symlinks'. I'll leave this issue open as a reminder to do that...

**Comment by parisk** [comment]
Would it work for you if this was an option in the [OS Filesystem constructor](https://pyfilesystem2.readthedocs.io/en/latest/reference/osfs.html#fs.osfs.OSFS) (e.g. `follow_symlinks=True`)?

This should imply:

- Usage of [`os.lstat`](https://docs.python.org/3/library/os.html#os.lstat), instead of [`os.stat`](https://docs.python.org/3/library/os.html#os.stat)
- Check if symlink target exists within the file system's boundaries
- Something else?

**Comment by willmcgugan** [comment]
The problem with that is that it doesn't let you decide which paths you want to follow symlinks and which you don't. I suspect the best solution would be to add a `followsymlinks` parameter to many of the methods. And possibly a "symlink" info namespace.

If you need symlinks in the short-term, you could get a [syspath](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.getsyspath) and do the `os.lstat` yourself.

**Comment by willmcgugan** [comment]
Actually, adding the 'symlink' namespace to Info looks straightforward and won't change the interface at all. That will at least expose the symlink stat information. I'll add that soon.

Adding `followsymlinks` to methods will require some thought, as it would be backwards incompatible.

**Comment by willmcgugan** [comment]
Will be looking at this shortly. Current thinking is that there will be a new `islink` method. And an a `lstat` info namespace in addition to `stat`.

**Comment by parisk** [comment]
Sounds like a good idea 😄.

**Comment by althonos** [comment]
Hi @willmcgugan, hi @parisk,

I just thought about what should happen with some edge-cases:
* What should happen when a symlink refers to another symlink referring to a resource ? Would the `followsymlinks` make the method use the actual resource, or only the second symlink ? 
* How to support symlinks that refer to inner resources (accessible through the filesystem) VS outer resources ?

### Retrieving targets

An idea I had was to add, instead of the syspath to the target to the `Info` struct, the actual `Info` of the target. But this would be quite useless when trying to retrieve the target path... except if the actual FS path was added to the `symlink` namespace as well.

Then the `symlink` namespace would have the following structures:
```python
{'target': <symlink '...>,         # an Info object with the same namespaces
 'syspath': '/...',                # a syspath to the current resource
 'path': '/...',}                  # the path to the current resource in the current FS
```

this way, set `syspath` to None when the current resource is not accessible through the OS, and set `path` to None when the current resource is not on the current FS.

Then, the `Info.target` property is a shortcut to `Info.get('link', 'target')`. There is no problem in creating an Info object:
* if it is inside the FS, then it's easy
* if it is outside, then the FS is probably relying on the OS filesystem, so it's easy too

If the filesystem doesn't support symlinking to external resource, raise a custom error.

Also, probably add the `is_link` property to `Info` as well, and use `FS.islink` as a shortcut to `FS.getinfo.islink`.


### Creating a symlink

If the FS supports symlinking, then the user should probably be able to create symlinks too. With the proposed structure, only add a `FS.link(path, target_path=None, target_sys_path=None)`.


### Edge cases
 
So, what do the edge-case become ? :
* What should happen when a symlink refers to another symlink referring to a resource ? Would the `followsymlinks` make the method use the actual resource, or only the second symlink ? --> with the above solution, one must go from one symlink to the other before accessing the actual resource. Maybe adding a `FS.follow(path)` method would help
* How to support symlinks that refer to inner resources (accessible through the filesystem) VS outer resources ? --> handled transparently here

**Comment by willmcgugan** [comment]
Good points there.

I think I might leave the `followsymlinks` discussion for later. Symlinks are problematic for a number of reasons, and I'm still trying to get that straight in my head.

With regards to the 'target'. It's easy enough (and useful) to report that in the info. Calculating a syspath if appropriate is also easy. But calculating a path that works on the current filesystem may be non-trivial in some cases.

Take for instance a MountFS, with two different filesystems mounted on `foo` and `bar`. There could be a symlink `foo/a` which references `../bar/a`.  Opening `foo/a` is perfectly valid, but the target path would reference an entirely different filesystem on the MountFS.

I've got PR in progress that at least reports the symlink information. It incorporates some of your suggestions. Might want to continue the discussion over there...

**Comment by willmcgugan** [comment]
I've added some symlink functionality

Some relevant info in the docs:

https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.islink
https://docs.pyfilesystem.org/en/latest/info.html#link-namespace

There is still work to do on symlinks, but v2.0.8 at least makes them visible from the PyFilesystem interface.
