### ISSUE TITLE
Consider closing on `__del__`

### ISSUE THREAD

**Issue by althonos** [PyFilesystem/pyfilesystem2#97]
Hi Will, 

@genben and I on althonos/fs.smbfs#1 are discussing whether `FS` objects should be closed on their `__del__` method, since in the current implementation they are not and they may not release the resources they acquired.

We could mimic the behaviour of Python *file* objects:
```python
def __del__(self):
   if not self.closed():
      warnings.warn("filesystem was not closed", ResourceWarning)
      self.close()
```

What do you think ?

**Comment by willmcgugan** [comment]
On face value that seems like a nice convenience for the developer (and I did that in fs1), but there are so many pitfalls with `__del__`. FS objects are much more complex beasts than file objects, and may have all sorts of references to other objects. Which means that you can't be certain what order they will be closed in. Consequently you can get bugs (or warnings) that appear only occasionally from one run to the next; tests are harder; things can behave differently depending on the scope you created the FS object; and the there are major differences across Python implementations (pypy in particular). 

Which is why in fs2 I was reluctant to use them. Even the mere presence of a `__del__` method can change the behaviour of the garbage collector.

If a context manager isn't appropriate, then I'd say that an app should define some kind of shut-down hook to close any filesystems. Most frameworks, gui or web, will provide some way of doing that. Alternatively there's always the weakref or atexit modules.

I could be persuaded otherwise, but I strongly suspect `FS.__del__` would be more trouble than its worth...

**Comment by althonos** [comment]
I have the same opinion actually. It is said in the Zen of Python "Explicit is better than implicit" so if you want the filesystem to be closed, then you should close it.

I agree that 
```python
fs.open_fs("...")
atexit.register(fs.close)
``` 
is probably the most sensible option if you really don't want to use contexts.

**Comment by genben** [comment]
Although I agree with Will regarding his preferences to not define `FS.__del__` method on the base file system class, I still think that such method should be added to the file system implementation classes, like `fs.sshfs.SSHFS` and and `fs.smbfs.SMBFS`.

The following code should not leak resources:

    fs = SMBFS(...)
    del fs

Right now, both SMBFS and SSHFS establish TCP connection to the remote servers and such connection is left opened after the file system object is destroyed. I think, it is fair that all internally created objects are destroyed automatically when the parent class is destroyed. The knowledge about internals of the class should not be passed to the user of class.

It is not always possible to use contexts, atexit or other similar hooks. I will provide a simple example from our web application, which is not something unusual. We use Pyramid frameworks, I believe Django and other frameworks have similar design.

View function, here we open file and stream it to web browser: 

    @view_config(route_name='some_view')
    def stream_file(self):
        file = <open the file on the remote file system>
        response = Response(status='200 OK')
        response.app_iter = FileIter(file)
        response.content_length = file_size
        return response

We cannot use contexts here because the file object should stay alive beyond this function scope. Also, we cannot close the file system object right here, because the file is still referencing it. The file content will be read later by WSGI server code on upper level.

Pyramid frameworks provides the hook `add_finished_callback`, which is called automatically at the very end of request processing. We tried to use it and close the file system explicitly insode the hook. But the file read operations are done by WSGI server on higher level, when the Pyramid request processing is done (i.e. hook is called already). As a result, the we have the exception when file object is read by WSGI server code.

So, in this simple example (we have more complex examples in our application), we cannot close the `FS` object until all files referencing it are closed as well. And the life cycle of the file object is beyond of our application control. We could add `__del__` method to the file object itself and implement our own reference counting between file objects to file system object. But that would be very ugly. 

I think, `__del__` method should be used without fears where it is reasonable/necessary. For example, paramiko uses it in very similar scenario. One of examples:

    class BufferedFile (ClosingContextManager): 
        ...
        def __del__(self):
            self.close()

**Comment by willmcgugan** [comment]
Hi @genben, 

I use pyfilesystem in my web-apps, albeit not pyramid. I take a different approach. The FS objects are created when the server is initialized and exist for the lifetime of the server (and closed only when the server exits). 

I close the file object explicitly with my `app_iter` as follows:

```python
def file_chunker(file, size=65536):
    """An iterator that reads a file in chunks."""
    read = file.read
    try:
        chunk = read(size)
        while chunk:
            yield chunk
            chunk = read(size)
    finally:
        file.close()
```

If there is no way around creating the FS object in the view, you could create an `app_iter` that closes the FS object. Something like this...

```python
def file_chunker(parent_fs, file, size=65536):
    """An iterator that reads a file in chunks."""
    read = file.read
    with parent_fs:
        try:
            chunk = read(size)
            while chunk:
                yield chunk
                chunk = read(size)
        finally:
            file.close()
```

Which you would add to your response like this...

```
response.app_iter = file_chunker(my_fs, file)
```

The generator object will hold on to a reference as long as it is iterating, then both the file and FS are explicitly closed.

Hope that helps!

**Comment by genben** [comment]
Hi Will,

Thank you for suggestions.

That will work in the first example. But there are other use cases, for example, our application allows user to download multiple files in bulk as a ZIP archive. It receives a list of file names in request and packs them into one ZIP file on flight during streaming to the web browser (i.e. no intermediary temporary file is used). The files potentially can reside on different file systems (one local, another on SFTP server, third on S3). In this case, we need to worry about closing multiple file system objects.

I don't say that it is not possible to create a solution for this case as well.
I just say, that FileSystems2 is supposed to provide abstraction layer to remote file systems and behave just like local file system (open file object, close it and do not worry about closing the file system itself). The user should expect to open a file from remote file system and pass this file-like object to any other parts of application without wrapping it into additional layer of abstraction.

Best regards,
Gennadiy

**Comment by willmcgugan** [comment]
Hi Gennadiy,

Relying on `__del__` to close things may seem like a no-brainer, but it is always going to be a worse solution than explicitly closing the filesystems. The reason I gave above will all apply to your use-case. You're most likely going to get a reference cycle with filesystem / file, and sockets  etc. will not be closed until whenever the gc kicks in.

Your example is interesting, but keeping track of the filesystems and closing them should not prohibitive. Not free, but much simpler than the streaming zip you implemented.

> I just say, that FileSystems2 is supposed to provide abstraction layer to remote file systems and behave just like local file system (open file object, close it and do not worry about closing the file system itself). 

I'm not sure that is applicable. It's true that devs don't typically manage the life cycle of the local file system, but it still needs to be managed. It's just that you rely on the OS to close the filesystem for you when you shut down. Since the OS isn't aware of PyFilesystem you have to do that manually.

Will

**Comment by willmcgugan** [comment]
Going to close this one for now. Hope I haven't discouraged @genben from using / contributing to PyFilesystem!

**Comment by genben** [comment]
Will,

I apologize for delay with response. The PyFilesystem project and the third-party file system implementations (SSHFS and SMBFS) are exactly what we need in our application. Actually, we wanted to implement something like that by ourselves, but then found your library, which does everything we need and even more. Thank you and @althonos for this tremendous work!

Regarding the current ticket, for the moment, we will use the forked versions of both SSHFS and SMBFS projects until we find better solution to manage life cycle of file system instances.

Our use cases are different from how you and probably @althonos use the PyFilesystem. In our multi-tenant applications, we have many dynamically configured short-lived file system instances versus a few relatively static instances.

Best regards,
Gennady
